name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build
        run: cargo build --verbose

  build_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: all features
        run: cargo build --verbose --all-features
      - name: no default features
        run: cargo build --verbose --no-default-features
      - name: 2D
        run: cargo build --verbose --no-default-features --features 2D
      - name: 3D
        run: cargo build --verbose --no-default-features --features 3D
      - name: auto coloring 2D
        run: cargo build --verbose --no-default-features --features "auto-coloring 2D"
      - name: auto coloring 3D
        run: cargo build --verbose --no-default-features --features "auto-coloring 3D"

  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build 2d game of life
        run: cargo clippy --all-features --example 2d_game_of_life
      - name: build 3d game of life
        run: cargo clippy --all-features --example 3d_game_of_life
      - name: build 2d immigration game
        run: cargo clippy --all-features --example 2d_immigration_game
      - name: build 2d rainbow game
        run: cargo clippy --all-features --example 2d_rainbow_game
      - name: build 2d color cyclic
        run: cargo clippy --all-features --example 2d_cyclic_colors
      - name: build 2d rock paper scissor
        run: cargo clippy --example 2d_rock_paper_scissor

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: test
        run: cargo test --tests --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "rustfmt"
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo clippy installation
        run: rustup component add clippy
      - name: Cargo clippy check
        run: cargo clippy --all-features --all --tests -- -D warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: rustdoc
        run: cargo rustdoc --all-features -- -D warnings
